[tool.poetry]
name = "finalytics-spark"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "finalytics_spark", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
ipykernel = "^6.29.5"
pyyaml = "^6.0.2"
yfinance = "^0.2.51"
psycopg2-binary = "^2.9.10"
nbimporter = "^0.3.4"
nbformat = "^5.10.4"
pyspark = "3.5.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
